LR: 3e-5
NUM_ENVS: 1
NUM_STEPS: 2048
TOTAL_TIMESTEPS: 1e7
UPDATE_EPOCHS: 1
NUM_MINIBATCHES: 32
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.0
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: tanh
ANNEAL_LR: True
NORMALIZE_ENV: False
