LR: 3e-4
NUM_ENVS: 1
NUM_STEPS: 2048
TOTAL_TIMESTEPS: 1e6
UPDATE_EPOCHS: 10
NUM_MINIBATCHES: 32
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.0
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: tanh
ANNEAL_LR: False
NORMALIZE_ENV: True
DEBUG: True
ENV_NAME: hopper
ENV_SOURCE: "brax"
BACKEND: "spring"
POLICY_CLASS: "continuous"
