env:
  sys_params:
    # solver: mujoco.mjtSolver.mjSOL_NEWTON
    # disableflags: mujoco.mjtDisableBit.mjDSBL_EULERDAMP
    # iterations: 1
    # ls_iterations: 4
    timestep: 0.0001
    # ls_tolerance: 0.0000001
    # mpr_tolerance: 1e-7
    # mpr_iterations: 60
