LR: 3e-4
NUM_ENVS: 2
NUM_STEPS: 1000
TOTAL_TIMESTEPS: 1e7
UPDATE_EPOCHS: 10
NUM_MINIBATCHES: 50
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.0
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: tanh
ANNEAL_LR: True
NORMALIZE_ENV: True
DEBUG: True
ENV_NAME: swimmer
ENV_SOURCE: "brax"
POLICY_CLASS: "continuous"
